### ISSUE TITLE
Client side button for SSID, passphrase and country only set ssid

### ISSUE THREAD

**Issue by kirkdwilson** [RT-coding-team/cbadmin#7]

**Comment by derekmaxson** [comment]
Fix in cbadmin to properly load the client wifi values: https://github.com/RT-coding-team/cbadmin/commit/89260bc91fa86b6b8350eaab23e56fc5d4e88440

**Comment by derekmaxson** [comment]
Fix in Connectbox-pi to api.py and ConnectBoxmanage.sh to properly handle client wifi values: https://github.com/ConnectBox/connectbox-pi/commit/af4ca2bdf4d5e6ebd833de56aadda0677b6cd43e
